import type { Metadata } from "next";//什么意思
// 这行代码导入了 Next.js 中的 Metadata 类型。Metadata 是一个接口，用于定义页面的元数据，例如标题、描述、关键字等。这些元数据可以帮助搜索引擎更好地理解页面内容，并在搜索结果中显示相关信息。在这个代码中，Metadata 类型被用来定义页面的标题和描述。
import { Geist, Geist_Mono } from "next/font/google";//这行代码导入了 Next.js 中的 Geist 和 Geist_Mono 字体。这些字体是从 Google Fonts 提供的，可以在应用程序中使用。通过导入这些字体，可以在应用程序中使用它们来设置文本的样式，从而提高应用程序的视觉效果和可读性。
import "./globals.css";//这行代码导入了一个全局的 CSS 文件，名为 globals.css。这个文件通常包含一些全局样式规则，这些规则会应用到整个应用程序中的所有组件和页面。通过导入这个文件，可以确保这些样式在整个应用程序中生效，从而保持一致的外观和感觉。

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});//这段代码创建了一个名为 geistSans 的字体对象，使用了 Geist 字体。variable 属性指定了一个 CSS 变量名，用于在样式中引用这个字体。subsets 属性指定了要加载的字符子集，这里是 "latin"，表示只加载拉丁字符。这种方式可以优化字体加载性能，因为只加载需要的字符集，而不是整个字体文件。通过使用这个字体对象，可以在应用程序中使用 Geist 字体来设置文本的样式。

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});//这段代码创建了一个名为 geistMono 的字体对象，使用了 Geist Mono 字体。variable 属性指定了一个 CSS 变量名，用于在样式中引用这个字体。subsets 属性指定了要加载的字符子集，这里是 "latin"，表示只加载拉丁字符。这种方式可以优化字体加载性能，因为只加载需要的字符集，而不是整个字体文件。通过使用这个字体对象，可以在应用程序中使用 Geist Mono 字体来设置文本的样式。

export const metadata: Metadata = {
  title: "桌宠养成计划",
  description: "Generated by create next app",
};//这段代码定义了一个名为 metadata 的常量，类型为 Metadata。这个对象包含了页面的元数据，其中 title 属性设置了页面的标题为 "Create Next App"，description 属性设置了页面的描述为 "Generated by create next app"。这些元数据可以帮助搜索引擎更好地理解页面内容，并在搜索结果中显示相关信息。

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {//下面这些是在实现什么
  // 这段代码定义了一个名为 RootLayout 的 React 组件，它接受一个 props 对象，其中包含一个 children 属性，类型为 React.ReactNode。这个组件是一个布局组件，用于包裹应用程序中的其他组件和页面。通过使用 RootLayout 组件，可以在整个应用程序中保持一致的布局和样式。在这个组件中，children 属性表示被包裹的子组件或页面内容，这些内容将被渲染在布局中。
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
